#ci.gocd.yaml
pipelines:
  springGocd:
    group: springGocd
    materials:
      template:
        auto_update: true
        destination: template
        git: 'git@github.com:shinobicars/springgocd.git'
        branch: 'master'

    stages:
      - defaultStage: # name of stage
          clean_workspace: true
          jobs:
            defaultJob:
              tasks:
                - exec:
                    command: '/bin/bash'
                    arguments:
                      - '-c'
                      - './gradlew clean build -i'
                    working_directory: template
      - anotherStage: # name of stage
          clean_workspace: true
          jobs:
            defaultJob:
              tasks:
               - fetch:
                   pipeline: springGocd
                   stage: defaultStage
                   job: defaultJob
                   source: template/